version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "#Admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1438:1433"

  template:
    image: ${DOCKER_REGISTRY-}template
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Initial Catalog=FinanceUnitDB;User ID=sa;password=#Admin123;MultipleActiveResultSets=true"
    ports:
      - "14800:80"
    depends_on:
      - db
