version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "#Admin123"
        ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    networks:
      - financeunit

  template.api:
    image: ${DOCKER_REGISTRY-}unikboligfinancefinanceunitapi
    build:
      context: .
      dockerfile: Unik.Bolig.Finance.Financeunit.API/Dockerfile
    environment:
      ConnectionStrings__DBConnection: "Server=db,1433;Initial Catalog=FinanceUnitDB;User ID=sa;password=#Admin123;MultipleActiveResultSets=true"
    networks:
      - financeunit
    depends_on:
      - db  
networks:
    financeunit:
        name: financeunit